server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:  # 数据源ds0
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user0?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123
      ds1:  # 数据源ds1
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user1?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:
            key-generator-column-name: user_id
            actual-data-nodes: ds${0..1}.t_user${0..2}    #数据节点,均匀分布
            database-strategy:  #分库策略
              inline: #行表达式
                sharding-column: user_id        #列名称，多个列以逗号分隔
                algorithm-expression: ds${user_id % 2}    #按模运算分配
            table-strategy:  #分表策略
              standard:
                sharding-column: user_id
                precise-algorithm-class-name: com.chengh.db.util.algorithm.IdSharingAlgorithm
                range-algorithm-class-name: com.chengh.db.util.algorithm.IdRangeSharingAlgorithm
          t_order:
            key-generator-column-name: id
            actual-data-nodes: ds${0..1}.t_order${0..2}    #数据节点,均匀分布
            database-strategy:  #分库策略
              inline: #行表达式
                sharding-column: user_id        #列名称，多个列以逗号分隔
                algorithm-expression: ds${user_id % 2}    #按模运算分配
            table-strategy:  #分表策略
              inline:
                sharding-column: user_id
                algorithm-expression: t_order${user_id % 3}
        default-key-generator-class-name: com.chengh.db.util.IdGenerator
        #default-data-source-name: ds1
        #binding-tables:
        #  - t_order,t_user